homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('Schedule/', views.Schedule, name = 'Schedule'),
    path('<int:pk>',views.Delete, name = 'Delete')
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Schedule/', include('homepage.urls')),
]

urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class index(models.Model):
	Day =  models.CharField(max_length=50)
	Date = models.DateField(blank = False)
	Time = models.TimeField()
	Name = models.TextField(max_length=50)

homepage/forms.py
from django import forms

class ScheduleForm(forms.Form):

	Day = forms.CharField(widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Day',
		'type' : 'text',
		'required' : True,
	}))

	Date = forms.DateField(widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'dd/mm/yyyy',
		'type' : 'date',
		'required' : True,
	}))

	Time = forms.TimeField(widget=forms.TextInput(attrs={
		'class': 'form-control',
		'type' : 'time',
		'required' : True,
	}))

	Name = forms.CharField(widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Activity Name',
		'type' : 'text',
		'required' : True,
	}))

homepage/views.py
from django.shortcuts import render, redirect
from .models import index as Jadwal
from .forms import ScheduleForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def Schedule(request):
	if request.method == "POST":
		form = ScheduleForm(request.POST)
		if form.is_valid():
			sched = Jadwal()
			sched.Day = form.cleaned_data['Day']
			sched.Date = form.cleaned_data['Date']
			sched.Time = form.cleaned_data['Time']
			sched.Name= form.cleaned_data['Name']
			sched.save()
		return redirect('/Schedule')
	else:
		schedule = Jadwal.objects.all()
		form = ScheduleForm()
		response = {"sched":schedule, 'form' : form}
		return render(request,'Schedule.html', response)

def Delete(request, pk):
    if request.method == "POST":
        form = ScheduleForm(request.POST)
        if form.is_valid():
            sched = Jadwal()
            sched.Day = form.cleaned_data['Day']
            sched.Date = form.cleaned_data['Date']
            sched.Time = form.cleaned_data['Time']
            sched.Name = form.cleaned_data['Name']
            sched.save()
        return redirect('/Schedule')
    else:
        Jadwal.objects.filter(pk=pk).delete()
        data = Jadwal.objects.all()
        form = ScheduleForm()
        response = {"sched":data, 'form' : form}
        return render(request, 'Schedule.html', response)

homepage/templates/Schedule.html
<!DOCTYPE html>
{% load static %}
<html>

  <head>

  <meta charset="utf-8">

  <title>Jadwal</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'css/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">
  

  <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >

</head>
	<body>
		<section class="page-section" id="form">
    		<div class="container">
      			<div class="row">
          			<div class="col">
              			<form id="form" action="{% url 'homepage:Schedule' %}" method="POST">
                			{% csrf_token %}
                			{{ form }}
               				<div class="centre-items">
                  				<input type="submit" class="btn btn-primary" value="Add Schedule">
                			</div>
              			</form>
          		</div>
          		<div class="col">
            		<table class="table">
              			<thead>
                			<tr>
                  			<th scope="col">Day</th>
                  			<th scope="col">Date</th>
                  			<th scope="col">Time</th>
                  			<th scope="col">Name</th>
                        <th scope="col">Delete</th>
                			</tr>
              			</thead>
              			<tbody>
                			{% for Jadwal in sched %}
                  				<tr>
                  				<th scope="row">{{Jadwal.Day}}</th>
                  				<td>{{Jadwal.Date}}</td>
                  				<td>{{Jadwal.Time}}</td>
                  				<td>{{Jadwal.Name}}</td>
                          <td><a href="{% url 'homepage:Delete' pk=Jadwal.pk %}"><button class="btn btn-danger"></button></a></td>
                  				</tr>
                			{% endfor %}
              			</tbody>
            		</table>
     		 	</div>
    		</div>
  		</section>
	</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">

  <title>Steven</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'css/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">
  

  <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >




</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">My Profile</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Education</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portfolio">Skill</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'homepage:Schedule' %}">Form</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-white font-weight-bold">Hey, I'm <br> Steven Ciayadi</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5">I am a student in the Faculty of Computer Science<br>in University of Indonesia</p>
          <a class="btn btn-secondary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
        </div>
      </div>
    </div>
  </header>



  <!-- About Section -->
  <section class="page-section bg-transparent" id="about">
    <div class="container">
      <div class="row justify-content-end">
        <div class="col-lg-8 text-right">
          <!-- <h2 class="text-white mt-0">We've got what you need!</h2> -->
          <h4 class="text-black-120 font-weight-bold mb-4">Hi there, I'm Steven Ciayadi. <br> 
            I’m 18 years old. I’m a student <br>in Computer Science at <br>University of Indonesia.</h4 >
          <img src="https://files.catbox.moe/0c0jap.JPG" alt="Steven" width="300" height="300" class="rotateimg270" align="left">

          <a class="btn btn-light btn-xl js-scroll-trigger pull-bottom" href="#services">Get Started!</a>
          <!-- <a class="btn btn-secondary btn-xl js-scroll-trigger" href="#about">Find Out More</a> -->
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section class="page-section" id="services">
    <div class="container">
      <h2 class="text-center mt-0">Here’s what I ‘ve done so far</h2>
      <hr class="divider my-4">
      <div class="row">
        <div class="col-lg-12 col-md-6 text-left">
          <div class="mt-5">
            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
            <h3 class="h4 mb-4">SMAK 1 BPK PENABUR Jakarta</h3>
            <img src="https://files.catbox.moe/3ess1g.jpg" alt="Steven" width="300" height="200" style= "padding-right: 50px;">
            <p class="text-muted mb-0">This is the place where the story begin, I feel the charm of science and logic here, which was create the bliss of souls for me today. I am so happy.</p>
          </div>
        </div>
        <div class="col-lg-12 col-md-6 text-left">
          <div class="mt-5">
            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
            <h3 class="h4 mb-4">UNIVERSITAS INDONESIA</h3>
            <img src="https://files.catbox.moe/539x0y.jpg" alt="Steven" width="300" height="200" style= "padding-right: 50px;">
            <p class="text-muted mb-0">I'm currently studying Computer Science in University of Indonesia, Depok, Indonesia. I choose this to get a new knowledge of programming. I also have a new friend and colleague.</p>
          </div>
      </div>
    </div>
  </section>

  <!-- Portfolio Section -->
  <section id="portfolio">
    <div class="container-fluid p-0">
    <h2 class="text-center mt-0 mb-4">SKILLS</h2>
    	<div class="row no-gutters">
        <div class="col-lg-4 col-sm-6">
          
            <img class="img-fluid" src="https://files.catbox.moe/a2gtjn.png" >
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center">
                Python
              </div>

            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          
            <img class="img-fluid" src="https://files.catbox.moe/xq2h3u.jpg" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center">
                Java
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
         
            <img class="img-fluid" src="https://files.catbox.moe/6pt09a.png" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center" >
                Pascal
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          
            <img class="img-fluid" src="https://files.catbox.moe/zwfst0.png" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center">
                HTML
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          
            <img class="img-fluid" src="https://files.catbox.moe/rj71fc.png" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center">
                CSS
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          
            <img class="img-fluid" src="https://files.catbox.moe/6jzqnl.jpg" alt="">
            <div class="portfolio-box-caption p-3">
              <div class="project-category text-white-50">
                Category
              </div>
              <div class="project-name" style="text-align:center">
                JavaScript
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Let's Get In Touch!</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Ready to start your next project with me? Give me a call or send me an email and I will get back to you as soon as possible!</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+62 822-9337-0542</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <a class="d-block" href="mailto:stevenciayadi23@gmail.com">stevenciayadi23@gmail.com</a>
        </div>
      </div>
    </div>
  </section>

  <!-- <section class="page-section" id="form">
    <div class="container">
      <div class="row">
          <div class="col">
              <form id="form" action="{% url 'homepage:index' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="centre-items">
                  <input type="submit" class="btn btn-primary" value="Add Schedule">
                </div>
              </form>
          </div>
          <div class="col">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Day</th>
                  <th scope="col">Date</th>
                  <th scope="col">Time</th>
                  <th scope="col">Name</th>
                </tr>
              </thead>
              <tbody>
                {% for Jadwal in sched %}
                  <tr>
                  <th scope="row">{{Jadwal.Day}}</th>
                  <td>{{Jadwal.Date}}</td>
                  <td>{{Jadwal.Time}}</td>
                  <td>{{Jadwal.Name}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
      </div>
    </div>
  </section> -->


  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2019</div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>